n = input('Digite algo: ')

print('O tipo primitivo desse valor é',type(n))
print('É um número?', n.isnumeric())
print('É alfanumérico?', n.isalnum())
print('É alfabético?', n.isalpha())
print('Está só em minúsculas?', n.islower())
print('Está só em maiúsculas?', n.isupper())
print('É somente espaço?', n.isspace())
print('Está capitalizada?', n.istitle())
